name: "CI"

on:
  push:
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'

    - run: ./scripts/tests_setup
      env:
        SKIP_SERVER_INSTALL: true

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - name: Flake8
      run: flake8

  nose:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'

    - name: Install packages
      run: ./scripts/tests_setup

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - run: nosetests --logging-level=ERROR

  behave:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'

    - run: ./scripts/tests_setup

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - run: behave --format progress2 --logging-level=ERROR

  prodapi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'

    - run: ./scripts/tests_setup

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - name: prodapi-pytest
      run: cd prod_api && time pytest
